/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/run/printProgress 1000

/output/format hdf5
/output/filename data/photon_sensor_hits
/output/runname microscope

/scintillator/geom/material EJ200
/scintillator/geom/scintX 5 cm
/scintillator/geom/scintY 5 cm
/scintillator/geom/scintZ 1 cm
/scintillator/geom/posX 0 cm
/scintillator/geom/posY 0 cm
/scintillator/geom/posZ 0 cm

/sensor/geom/sensorX 5 cm
/sensor/geom/sensorY 5 cm
/sensor/geom/sensorThickness 0.1 mm
/sensor/geom/posX 0 cm
/sensor/geom/posY 0 cm
/sensor/geom/posZ 17.526 mm

/run/initialize

/gps/particle neutron
/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/centre 0.0 0.0 -10.0 cm
/gps/pos/radius 1.0 cm
/gps/ang/type beam2d
/gps/ang/rot1 1 0 0
/gps/ang/rot2 0 1 0
/gps/direction 0 0 1
/gps/ene/type Mono
/gps/ene/mono 6 MeV

/run/beamOn 1000
