/control/verbose 1
/run/verbose 1
/event/verbose 0
/tracking/verbose 0
/tracking/storeTrajectory 1

/scintillator/geom/material EJ200
/scintillator/geom/scintX 5 cm
/scintillator/geom/scintY 5 cm
/scintillator/geom/scintZ 1 cm
/scintillator/geom/posX 0 cm
/scintillator/geom/posY 0 cm
/scintillator/geom/posZ 0 cm

/sensor/geom/sensorX 5 cm
/sensor/geom/sensorY 5 cm
/sensor/geom/sensorThickness 0.1 mm
/sensor/geom/posX 0 cm
/sensor/geom/posY 0 cm
/sensor/geom/posZ 17.526 mm

/run/initialize

/vis/open OGL
/vis/viewer/set/style wireframe
/vis/drawVolume
/vis/scene/add/trajectories
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton cyan
/vis/modeling/trajectories/drawByParticleID-0/set neutron yellow
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts false
/vis/viewer/set/autoRefresh true
/vis/scene/endOfEventAction accumulate

/gps/particle neutron
/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/centre 0.0 0.0 -10.0 cm
/gps/pos/radius 1.0 cm
/gps/direction 0 0 1
/gps/ene/type Mono
/gps/ene/mono 2 MeV

/run/beamOn 100
