/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/run/printProgress 1000
/plastic/output/format hdf5
/plastic/output/hdf5File photon_sensor_hits.h5
/plastic/geom/material EJ200
/plastic/geom/scintX 5 cm
/plastic/geom/scintY 5 cm
/plastic/geom/scintZ 1 cm
/plastic/geom/sensorThickness 0.1 mm
/run/initialize

/gps/particle neutron
/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/centre 0.0 0.0 -10.0 cm
/gps/pos/radius 1.0 cm
/gps/ang/type beam2d
/gps/ang/rot1 1 0 0
/gps/ang/rot2 0 1 0
/gps/direction 0 0 1
/gps/ene/type Mono
/gps/ene/mono 6 MeV

/run/beamOn 10
